kind: Deployment
apiVersion: apps/v1
metadata: 
  name: react
  labels: 
    app: simple-frontend
spec: 
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
      matchLabels:
        app: simple-frontend
  template: 
    metadata: 
      labels:
        app: simple-frontend
    spec:
      containers:
        - name:  react
          image: fordax/simple-front:2.1
          ports:
            - containerPort: 80