kind: Service
apiVersion: v1
metadata:
  name:  flask-service
spec:
  type:  NodePort
  selector:
    app:  simple-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30036
      protocol: TCP