kind: Deployment
apiVersion: apps/v1
metadata: 
  name: flask-app
  labels: 
    app: simple-backend
spec: 
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
      matchLabels:
        app: simple-backend
  template: 
    metadata: 
      labels:
        app: simple-backend
    spec:
      containers:
        - image:  fordax/simple-back
          name:  flask-app
          ports:
            - containerPort: 5000